# Generated by Django 4.2.14 on 2024-07-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilla', '0002_question_questionchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionchoice',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
